[package]
name = "path-tracer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24.7", default-features = false, features = ["png"] }
nalgebra = { version = "0.32.3", features = ["rand"] }
rand = "0.8.5"
rand_distr = "0.4.3"
